<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Album Application</span></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Total Album</h2>
            </div>
            <div class="card-body">
                <h2 class="card-title">
                    111
                </h2>
            </div>
        </div>
    </div>
</div>
